name: Prettier Check

on:
  pull_request:
    branches:
      - main # 또는 기본 브랜치 이름
      - dev

jobs:
  lint_build_Check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies #패키지 버전 체크
        run: npm ci